### ISSUE TITLE
I am having issues figuring out the file path for the favicon and if my code is correct.

### ISSUE THREAD

**Issue by Aubzilla** [david63/david63-favicon#1]
The path I am using is;

	<link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32">
	<link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16">

Is this correct?? What is the correct file path?

**Comment by Aubzilla** [comment]
<link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16" />

**Comment by Aubzilla** [comment]
<link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32">
	<link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16">

**Comment by david63** [comment]
Not sure what you are trying to do but this extension only requires you to upload a favicon.ico file to the root of your board

**Comment by Aubzilla** [comment]
I am trying to install this into ext/david63/favicon/... instead of
ext/david63-favicon-master/david63/favicon/.....

I also already have a favicon I am trying to use with the main directory.
Should I just upload the favicon icons into my public_html folder??

**Comment by Aubzilla** [comment]
Ah ha! I have solved it!
